### ISSUE TITLE
Intro & Exit screens

### ISSUE THREAD

**Issue by LinusMuema** [jkuatdsc/form-builder#27]
### TO-DOs
- [ ] Create the Intro screen and its components
- [ ] Create the Exit screen and its components
- [ ] Handle navigation in each screen

### Nice to Haves
- [ ] Animate the start button using a pulse animation
- [ ] Animate the navigation transitions
