### ISSUE TITLE
Survey state management

### ISSUE THREAD

**Issue by LinusMuema** [jkuatdsc/form-builder#29]
In the SurveyViewmodel class, create a the form states to hold the states of all the fields of a single page the survey. All fields must have the `Validators.Required` validator. 

### TO-DO's
- [x] Create the different form states
- [x] Add field states to the specific form states
- [x] Add the respective validators in each of the field states
