### ISSUE TITLE
Survey validation

### ISSUE THREAD

**Issue by LinusMuema** [jkuatdsc/form-builder#30]
### TO-DOs
- [x] Implement the `validate on each screen` flow
- [x] Add the individual form validations
- [x] Implement the whole survey validation
- [x] Navigate to the error screens if needed

### Nice to have's
- [ ] Animate the navigation to the error screens
