### ISSUE TITLE
Tab layout

### ISSUE THREAD

**Issue by LinusMuema** [jkuatdsc/form-builder#31]
This includes the indicator at the top of the screen.

### TO-DO's
- [x] Create the TabLayout composable
- [x] Implement the state changes and update the UI on navigation

### Nice to have's
- [x] Animate the visibility on navigation 
- [x] Animate the transition on navigation
