### ISSUE TITLE
Navigation

### ISSUE THREAD

**Issue by LinusMuema** [jkuatdsc/form-builder#32]
This involves the buttons on each of the survey pages.

### TO-DO's
- [x] Add the buttons composable
- [x] Implement navigation between the survey pages
- [x] Start validations if needed
- [x] Navigate to ExitActivity if needed
